# Generated by Django 6.1.1 on 2026-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto_origen', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
                ('puerto_destino', models.CharField(default='Valparaíso', max_length=100)),
                ('tipo_ruta', models.CharField(blank=True, max_length=50, null=True)),
                ('tarifa_20_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_20_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_40_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_40_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_hq_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_hq_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transito_min', models.IntegerField()),
                ('transito_max', models.IntegerField()),
                ('fuente', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tarifas_maestras',
            },
        ),
    ]
